### ISSUE TITLE
Unable to install module gcadapter-oc-dkms/1.4 - Missing kernel headers

### ISSUE THREAD

**Issue by SSBMTonberry** [HannesMann/gcadapter-oc-kmod#4]
Hey!
So I tried to run the `gcadapter-oc-dkms-1.4-1-any.pkg.tar.zst` file, and ran into an issue.
I'm using Manjaro with the `4.14` kernel of Linux.
Tried to re-install as well after a full system upgrade, but didn't make much difference. This is the log from `pacman`:
```
Preparing...
Warning: gcadapter-oc-dkms-1.4-1 is up to date -- reinstalling
Resolving dependencies...
Checking inter-conflicts...
Checking keyring...
Checking integrity...
Loading packages files...
Checking file conflicts...
Checking available disk space...
==> Unable to remove module gcadapter-oc-dkms/1.4 for kernel 4.14.215-1-MANJARO: Not found in dkms status output.
Reinstalling gcadapter-oc-dkms (1.4-1)...
ldconfig: File /usr/lib/libORBit-2.so.0 is too small, not checked.
ldconfig: /usr/lib/libORBit-2.so.0 is not a symbolic link

Running post-transaction hooks...
Arming ConditionNeedsUpdate...
Install DKMS modules
==> Unable to install module gcadapter-oc-dkms/1.4 for kernel 4.14.215-1-MANJARO: Missing kernel headers.
Transaction successfully finished.
``` 

Any idea what could be the issue? For comparison: What system are you running? :slightly_smiling_face:

**Comment by HannesMann** [comment]
> Any idea what could be the issue?

You need to install kernel headers since you're building an out-of-tree module. I don't know what Manjaro calls their kernel but usually there's a package that ends in `-headers` you need to install (so if the kernel is called `linux` the headers are called `linux-headers`).

> For comparison: What system are you running?

I'm running stock Arch with Linux 5.10. 4.14 is an older kernel but that's not an issue since the latest kernel was 4.11 when this module was created :slightly_smiling_face:

**Comment by SSBMTonberry** [comment]
Thanks a lot!
Seems like a `sudo pacman -S linux414-headers` did the trick :)
